In [1]:
!python --version

Python 3.6.9


In [2]:
x = 3
print(x,type(x))

3 <class 'int'>


In [4]:
print(x+1)
print(x-1)
print(x*1)
print(x**3)
print(x%3)
print(x//3)

4
2
3
27
0
1


In [5]:
x = x+1
print(x)
x += 1
print(x)

4
5


In [7]:
t, f = True, False
print(type(t))
# boolean

<class 'bool'>


In [8]:
print(t and f)
print(t or f)
print(not t)
print(t != f)

False
True
False
True


In [9]:
hello = "hello"
world = "world"
print(hello, len(hello))

hello 5


In [10]:
hw = hello + ' ' + world
print(hw)

hello world


In [11]:
hw12 = '%s %s %d' % (hello, world, 12)
print(hw12)

hello world 12


In [12]:
s = "hello"
print(s.capitalize())
print(s.upper())
print(s.replace('l','(ell)'))
print(' world '.strip())

Hello
HELLO
he(ell)(ell)o
world


In [15]:
xs = [3,1,2]
# xs[0] xs[1] xs[2] == xs[-1]
print(xs,xs[0])
print(xs[-1])

[3, 1, 2] 2
2


In [16]:
xs[2] = 'foo'
print(xs)

[3, 1, 'foo']


In [17]:
xs.append('bar')
print(xs)

[3, 1, 'foo', 'bar']


In [18]:
x = xs.pop()
print(x, xs)

bar [3, 1, 'foo']


In [26]:
x = xs[0:1]
x1 = xs[0]
print(x, x1, xs)

[3] 3 [3, 1, 'foo']


In [27]:
animals = ['cat','dog','monkey']
for animal in animals:
    print(animal)

cat
dog
monkey


In [28]:
for idx, animal in enumerate(animals):
    print(idx, animal)

0 cat
1 dog
2 monkey


In [30]:
nums = range(5)
print(list(nums))

[0, 1, 2, 3, 4]


In [32]:
type(range(5))

range

In [33]:
for i in range(5):
    print(i)

0
1
2
3
4


In [34]:
nums = [0,1,2,3,4]
squares = []
for i in nums:
    squares.append(i ** 2)
print(squares)

[0, 1, 4, 9, 16]


In [39]:
squares = [i ** 2 for i in nums if i % 2 == 0]
print(squares)

[0, 4, 16]


In [40]:
num_num = [[1,2],[3,4],[5,6]]
for num in num_num:
    for i in num:
        print(i)

1
2
3
4
5
6


In [48]:
temp_list = [i for num in num_num for i in num]
print(temp_list)
for ii in temp_list:
    print(ii)

[1, 2, 3, 4, 5, 6]
1
2
3
4
5
6


In [43]:
d = {'cat':'cute', 'dog':'furry'}
print(d['dog'])
print('cat' in d)

furry
True


In [45]:
d['fish'] = 'wet'
print(d['fish'])

wet


In [46]:
d.get('fish')

'wet'

In [0]:
import numpy as np

In [51]:
a = np.array([1,2,3])
print(type(a), a.shape, a[0], a[1], a[2])
a[0] = 5
print(a)

<class 'numpy.ndarray'> (3,) 1 2 3
[5 2 3]


In [52]:
b = np.array([[1,2,3],[4,5,6]])
print(b)

[[1 2 3]
 [4 5 6]]


In [53]:
print(b.shape)

(2, 3)


In [54]:
print(b[0,0],b[0,1],b[1,0])

1 2 4


In [57]:
print(b[0:2,0],b[0,0:2],b[1,0])

[1 4] [1 2] 4


In [58]:
a = np.zeros((2,2))
print(a)

[[0. 0.]
 [0. 0.]]


In [59]:
a = np.ones((2,2))
print(a)

[[1. 1.]
 [1. 1.]]


In [60]:
a = np.full((2,2),7)
print(a)

[[7 7]
 [7 7]]


In [61]:
a = np.eye(2)
print(a)

[[1. 0.]
 [0. 1.]]


In [63]:
a = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(a)
b = a[:2,1:3]
print(b)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[2 3]
 [6 7]]


In [64]:
row_r1 = a[1,:]
row_r2 = a[1:2,:]
row_r3 = a[[1],:]

print(row_r1,row_r1.shape)
print(row_r2,row_r2.shape)
print(row_r3,row_r3.shape)

[5 6 7 8] (4,)
[[5 6 7 8]] (1, 4)
[[5 6 7 8]] (1, 4)


In [65]:
row_r4 = a[[0,2],:]
print(row_r4,row_r4.shape)

[[ 1  2  3  4]
 [ 9 10 11 12]] (2, 4)


In [68]:
a = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
print(a)
print(a[range(4),2])

# np.arange() 는 range() 와 비슷한 함수

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[ 3  6  9 12]


In [72]:
a = np.array([[1,2],[3,4],[5,6]])

bool_idx = (a == 2)
print(a)
print(bool_idx)

[[1 2]
 [3 4]
 [5 6]]
[[False  True]
 [False False]
 [False False]]


In [71]:
print(a[a>2])

[3 4 5 6]


In [73]:
x = np.array([[1,2],[3,4]], dtype=np.float64)
y = np.array([[5,6],[7,8]], dtype=np.float64)

print(x+y)
print(np.add(x,y))

[[ 6.  8.]
 [10. 12.]]
[[ 6.  8.]
 [10. 12.]]


In [75]:
print(x-y)
print(np.subtract(x,y))

[[-4. -4.]
 [-4. -4.]]
[[-4. -4.]
 [-4. -4.]]


In [77]:
print(x)
print(y)
print(x*y)
print(np.multiply(x,y))

[[1. 2.]
 [3. 4.]]
[[5. 6.]
 [7. 8.]]
[[ 5. 12.]
 [21. 32.]]
[[ 5. 12.]
 [21. 32.]]


In [78]:
print(x)
print(y)
print(x/y)
print(np.divide(x,y))

[[1. 2.]
 [3. 4.]]
[[5. 6.]
 [7. 8.]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]


In [80]:
print(x.dot(y))
print(np.dot(x,y))

[[19. 22.]
 [43. 50.]]
[[19. 22.]
 [43. 50.]]


In [82]:
print(x)

print(np.sum(x))
print(np.sum(x, axis=0))
print(np.sum(x, axis=1))

[[1. 2.]
 [3. 4.]]
10.0
[4. 6.]
[3. 7.]


In [85]:
print(x)
print(x.T)
x = x.T
print(x)

[[1. 2.]
 [3. 4.]]
[[1. 3.]
 [2. 4.]]
[[1. 3.]
 [2. 4.]]


In [87]:
x = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
v = np.array([1,0,1])
y = np.empty_like(x)

print(x)
print(v)
print(y)

for i in range(4):
    y[i,:] = x[i,:] + v

print(y)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[1 0 1]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


In [94]:
vv = np.tile(v,(4,1))

print(vv)

y = x + vv
print(y)

[[1 0 1]
 [1 0 1]
 [1 0 1]
 [1 0 1]]
[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


In [90]:
aa = np.zeros((3,4))
y = np.empty_like(aa)
yy = np.copy(x)

print(x)
print(y)
print(yy)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[[3.31247538e-316 2.56761491e-312 2.20687562e-312 2.33419537e-312]
 [8.48798317e-313 2.22809558e-312 2.14321575e-312 6.79038653e-313]
 [2.14321575e-312 2.29175545e-312 8.70018274e-313 1.46030983e-319]]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
